## **Tic-Tac-Toe implemantation with a human vs Min-Max AI Agent**
Simply run the code below and follow the instructions in the terminal to play the game. The AI will determine its moves using the Min-Max algorithm, and the player will be prompted to enter their moves using the keyboard.
   

In [2]:
import random

def draw_board(board):
    print(board[0], "|", board[1], "|", board[2])
    print("---------")
    print(board[3], "|", board[4], "|", board[5])
    print("---------")
    print(board[6], "|", board[7], "|", board[8])

def get_player_move(board):
    valid_move = False
    while not valid_move:
        move = input("Enter your move (0-8): ")
        if move.isdigit() and int(move) >= 0 and int(move) <= 8 and board[int(move)] == " ":
            valid_move = True
        else:
            print("Invalid move, try again.")
    return int(move)

def get_ai_move(board):
    best_score = -float("inf")
    best_move = None
    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = min_max(board, False)
            board[i] = " "
            if score > best_score:
                best_score = score
                best_move = i
    return best_move

def min_max(board, is_maximizing):
    if check_winner(board):
        if is_maximizing:
            return -1
        else:
            return 1
    elif check_tie(board):
        return 0
    elif is_maximizing:
        best_score = -float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score = min_max(board, False)
                board[i] = " "
                if score > best_score:
                    best_score = score
        return best_score
    else:
        best_score = float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score = min_max(board, True)
                board[i] = " "
                if score < best_score:
                    best_score = score
        return best_score

def check_winner(board):
    for i in range(3):
        if board[i] != " " and board[i] == board[i + 3] and board[i] == board[i + 6]:
            return True
    for i in range(0, 9, 3):
        if board[i] != " " and board[i] == board[i + 1] and board[i] == board[i + 2]:
            return True
    if board[0] != " " and board[0] == board[4] and board[0] == board[8]:
        return True
    if board[2] != " " and board[2] == board[4] and board[2] == board[6]:
        return True
    return False

def check_tie(board):
    return not " " in board


def play_game():
    board = [" " for _ in range(9)]
    player_turn = random.choice([True, False])
    print("Welcome to Tic-Tac-Toe!")
    draw_board(board)
    while True:
        if player_turn:
            move = get_player_move(board)
            board[move] = "X"
        else:
            print("AI is making a move...")
            move = get_ai_move(board)
            board[move] = "O"
        draw_board(board)
        if check_winner(board):
            if player_turn:
                print("Congratulations! You win!")
            else:
                print("Sorry, the AI wins.")
            break
        elif check_tie(board):
            print("It's a tie!")
            break
        player_turn = not player_turn

if __name__ == "__main__":
    play_game()

Welcome to Tic-Tac-Toe!
  |   |  
---------
  |   |  
---------
  |   |  
Enter your move (0-8): 4
  |   |  
---------
  | X |  
---------
  |   |  
AI is making a move...
O |   |  
---------
  | X |  
---------
  |   |  
Enter your move (0-8): 5
O |   |  
---------
  | X | X
---------
  |   |  
AI is making a move...
O |   |  
---------
O | X | X
---------
  |   |  
Enter your move (0-8): 6
O |   |  
---------
O | X | X
---------
X |   |  
AI is making a move...
O |   | O
---------
O | X | X
---------
X |   |  
Enter your move (0-8): 1
O | X | O
---------
O | X | X
---------
X |   |  
AI is making a move...
O | X | O
---------
O | X | X
---------
X | O |  
Enter your move (0-8): 8
O | X | O
---------
O | X | X
---------
X | O | X
It's a tie!


## **Explanation**
The minimax algorithm is used in the implementation to determine the best move for the computer player. The minimax algorithm is a recursive function that explores all possible game states and chooses the best move for the computer player. The "O" symbol represents the computer player.

Several functions are defined in the code:



draw_board: prints the game board's current state to the console.



get_player_move: asks the human player for their move, validates the input, and returns the chosen move as an integer.



get_ai_move: employs the minimax algorithm to determine the best move for the computer player and returns the result as an integer.
The recursive function that implements the minimax algorithm is min_max(board, is_maximizing). Returns the current game state's score, with positive scores indicating a computer player's winning position, negative scores indicating a human player's winning position, and zero indicating a tie.

check_winner: determines whether either player has won the game by examining all possible winning cell combinations.

check_tie: determines whether the game is a tie by examining whether all cells are filled.

Finally, the code defines the play_game() function, which initializes the game board, picks a starting player at random, and loops through each turn until a winner is determined or the game ends in a tie. After each turn, the game state is printed to the console, and the winner is announced at the end. The check name == "main" at the end of the code ensures that the game is only played if the code is run as a standalone program rather than as a module.


## **A human's implementation of a Tic-Tac-Toe game against an AI agent using Alpha-Beta pruning:**

In [3]:
import random

def draw_board(board):
    print(board[0], "|", board[1], "|", board[2])
    print("---------")
    print(board[3], "|", board[4], "|", board[5])
    print("---------")
    print(board[6], "|", board[7], "|", board[8])

def get_player_move(board):
    valid_move = False
    while not valid_move:
        move = input("Enter your move (0-8): ")
        if move.isdigit() and int(move) in range(9) and board[int(move)] == " ":
            return int(move)
        else:
            print("Invalid move, please try again.")

def check_winner(board):
    winning_positions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]
    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] != " ":
            return True
    return False

def check_tie(board):
    return " " not in board

def get_ai_move(board):
    _, move = minimax(board, True, -float("inf"), float("inf"))
    return move

def minimax(board, is_maximizing_player, alpha, beta):
    if check_winner(board):
        return (-1 if is_maximizing_player else 1, None)
    elif check_tie(board):
        return (0, None)

    if is_maximizing_player:
        best_score = -float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score, _ = minimax(board, False, alpha, beta)
                board[i] = " "
                if score > best_score:
                    best_score = score
                    best_move = i
                alpha = max(alpha, best_score)
                if beta <= alpha:
                    break
        return (best_score, best_move)
    else:
        best_score = float("inf")
        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score, _ = minimax(board, True, alpha, beta)
                board[i] = " "
                if score < best_score:
                    best_score = score
                    best_move = i
                beta = min(beta, best_score)
                if beta <= alpha:
                    break
        return (best_score, best_move)


def play_game():
    board = [" " for _ in range(9)]
    player_turn = random.choice([True, False])
    print("Welcome to Tic-Tac-Toe!")
    draw_board(board)
    while True:
        if player_turn:
            move = get_player_move(board)
            board[move] = "X"
        else:
            print("AI is making a move...")
            move = get_ai_move(board)
            board[move] = "O"
        draw_board(board)
        if check_winner(board):
            if player_turn:
                print("Congratulations! You win!")
            else:
                print("Sorry, the AI wins.")
            break
        elif check_tie(board):
            print("It's a tie!")
            break
        player_turn = not player_turn

if __name__ == "__main__":
    play_game()

Welcome to Tic-Tac-Toe!
  |   |  
---------
  |   |  
---------
  |   |  
AI is making a move...
O |   |  
---------
  |   |  
---------
  |   |  
Enter your move (0-8): 4
O |   |  
---------
  | X |  
---------
  |   |  
AI is making a move...
O | O |  
---------
  | X |  
---------
  |   |  
Enter your move (0-8): 2
O | O | X
---------
  | X |  
---------
  |   |  
AI is making a move...
O | O | X
---------
  | X |  
---------
O |   |  
Enter your move (0-8): 3
O | O | X
---------
X | X |  
---------
O |   |  
AI is making a move...
O | O | X
---------
X | X | O
---------
O |   |  
Enter your move (0-8): 8
O | O | X
---------
X | X | O
---------
O |   | X
AI is making a move...
O | O | X
---------
X | X | O
---------
O | O | X
It's a tie!


## **Explanation**
To select who goes first at random, the random module is imported at the beginning of the function.

The draw_board function prints the board's current state in a readable way after receiving a list that represents it.

Once a legal move is entered, the get_player_move method asks the user for input and returns the move that was selected. An integer that falls between 0 and 8 (inclusive) that corresponds to an empty square on the board is a legitimate move.
The function check_winner verifies if any player has won by looking at the board. It accomplishes this by examining each and every winning combination that could occur in the rows, columns, and diagonals of the board. The function returns True if any of these combinations have three instances of the same symbol (X or O). If not, False is returned.

To determine whether the game has ended in a tie, the check_tie function looks over the board. When there are no more blank squares on the board, this is accurate.
The minimax algorithm is used by the get_ai_move function to determine the optimal move for the AI player. The move that produces the best result for the AI player is determined by the minimax algorithm, a recursive function that simulates every move that could be made on the board. Both the chosen move's index and the score related to it are returned by the function.
Recursively calling the minimax function simulates every move that could be made on the board. It receives the board state as input, a boolean value indicating whether the AI or the human player is currently maximizing or minimizing, and two parameters, alpha and beta, which are used to refine the search tree and boost algorithmic efficiency. The best move index and score are returned by the function.

The player who goes first is chosen at random by the play_game function, which also initializes an empty board. The program then repeatedly runs through each turn, asking the player to input or invoking get_ai_move to determine the AI's next move. The check_winner and check_tie functions are called to ascertain whether the game has ended after the board is redrawn following each turn. In that case, the game concludes with the winner—or lack thereof—being declared. If not, the other player's turn is added to the loop.

Lastly, play_game is only called if the script is executed directly, meaning it is not imported as a module, thanks to the if name == "main" line at the bottom of the code.



## **Using Q-learning to implement a human-versus-AI Tic-Tac-Toe match:**

In [5]:
import numpy as np
import random

# Initialize Q-values
Q = {}

# Hyperparameters
alpha = 0.1 # learning rate
gamma = 0.9 # discount factor
epsilon = 0.1 # exploration probability

# Define game state and action space
state_space = [[0, 0, 0] for i in range(3)]
action_space = [(i, j) for i in range(3) for j in range(3)]

# Define reward function
def reward(state):
    if any(sum(row) == 3 for row in state): # check rows
        return 1
    if any(sum(col) == 3 for col in zip(*state)): # check columns
        return 1
    if sum(state[i][i] for i in range(3)) == 3: # check diagonal
        return 1
    if sum(state[i][2-i] for i in range(3)) == 3: # check diagonal
        return 1
    if any(sum(row) == -3 for row in state): # check rows
        return -1
    if any(sum(col) == -3 for col in zip(*state)): # check columns
        return -1
    if sum(state[i][i] for i in range(3)) == -3: # check diagonal
        return -1
    if sum(state[i][2-i] for i in range(3)) == -3: # check diagonal
        return -1
    return 0

# Define epsilon-greedy policy
def epsilon_greedy_policy(state, epsilon):
    if random.uniform(0, 1) < epsilon:
        return random.choice(action_space)
    else:
        #q_values = [Q.get((tuple(state), action), 0) for action in action_space]
        q_values = [Q.get((tuple(map(tuple, state)), action), 0) for action in action_space]
        max_q_value = max(q_values)
        count = q_values.count(max_q_value)
        if count > 1:
            best_actions = [action_space[i] for i in range(len(action_space)) if q_values[i] == max_q_value]
            return random.choice(best_actions)
        else:
            return action_space[q_values.index(max_q_value)]

# Define Q-learning algorithm
#def q_learning(state, action, next_state, reward, alpha, gamma):
#   max_next_q_value = max([Q.get((tuple(next_state), next_action), 0) for next_action in action_space])
#   current_q_value = Q.get((tuple(state), action), 0)
#    Q[(tuple(state), action)] = current_q_value + alpha * (reward + gamma * max_next_q_value - current_q_value)

def q_learning(state, action, next_state, reward, alpha, gamma):
    state = tuple(map(tuple, state))
    next_state = tuple(map(tuple, next_state))
    # Get Q-value for current state-action pair
    q_value = Q.get((state, action), 0)
    # Compute the maximum Q-value for the next state
    #max_q_value = max([Q.get((next_state, a), 0) for a in action_space(next_state)])
    max_q_value = max([Q.get((next_state, a), 0) for a in action_space])
    # Update Q-value using Q-learning formula
    #Q[(state, action)] = q_value + alpha * (reward + gamma * max_q_value - q_value)
    Q[tuple(map(tuple, state)), action] = q_value + alpha * (reward + gamma * max_q_value - q_value)


# Initialize game
state = state_space.copy()
while True:
    # Human player's turn
    print("Current state:")
    print(np.array(state))
    #row, col = input("Enter row and column (0-2): ").split()
    input_str = input("Enter row and column (0-2): ")
    row, col = input_str.split('-') if '-' in input_str else input_str.split()
    row, col = int(row), int(col)
    if state[row][col] != 0:
        print("Invalid move, try again.")
        continue
    state[row][col] = 1
    reward_value = reward(state)
    if reward_value != 0:
        print("You won!")
        break
    if all(all(row) for row in state):
        print("Tie!")
        break
    # AI agent's turn
    action = epsilon_greedy_policy(state, epsilon)
    state[action[0]][action[1]] = -1
    reward_value = reward(state)

    if reward_value != 0:
        print("You lost!")
        break
    if all(all(row) for row in state):
        print("Tie!")
        break

# Update Q-values
q_learning(state, action, state, reward_value, alpha, gamma)

Current state:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter row and column (0-2): 0-1
Current state:
[[ 0 -1  0]
 [ 0  0  0]
 [ 0  0  0]]
Enter row and column (0-2): 1-1
Current state:
[[ 0 -1  0]
 [ 0  1  0]
 [ 0  0 -1]]
Enter row and column (0-2): 1-2
Current state:
[[ 0 -1  0]
 [ 0 -1  1]
 [ 0  0 -1]]
Enter row and column (0-2): 2-1
Current state:
[[ 0 -1  0]
 [ 0 -1  1]
 [ 0  1 -1]]
Enter row and column (0-2): 2-2
Invalid move, try again.
Current state:
[[ 0 -1  0]
 [ 0 -1  1]
 [ 0  1 -1]]
Enter row and column (0-2): 2-1
Invalid move, try again.
Current state:
[[ 0 -1  0]
 [ 0 -1  1]
 [ 0  1 -1]]
Enter row and column (0-2): 0-0
You lost!


## **Explanation**
A few variables and functions are defined at the beginning of the program:

Q: a dictionary where state-action pair Q-values are kept Alpha is the rate of learning. Gamma is the factor of discount. Epsilon: the likelihood of exploration state_space: a list that shows how the game board is currently configured action_space: a list containing every action that could be taken reward(state): a function that determines the incentive for a specific condition The function epsilon_greedy_policy(state, epsilon) applies the epsilon-greedy policy to action selection. A function called q_learning(state, action, next_state, reward, alpha, gamma) modifies the Q-value for a specific state-action pair. After initializing the game board, the program initiates a loop in which moves are made alternately by the AI agent and the human player.

The program asks the user to enter the row and column of their move during the human player's turn while printing the current state of the game board. The program updates the game board and determines whether the game is over if the move is valid. The software prints the outcome and ends the loop if the game is over.

The program updates the game board, checks to see if the game is over, and chooses an action based on the epsilon-greedy policy during the AI agent's turn. The software prints the outcome and ends the loop if the game is over.

The software updates the Q-value for the final state-action pair by calling the q_learning() function after the game is finished.

## **Using all AI agents (MIN_MAX, ALPHA_BETA, Q-LEARNING) to implement TIC-TAC-TOE**

In [6]:
from random import choice
from math import inf

board = [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]

def Gameboard(board):
    chars = {1: 'X', -1: 'O', 0: ' '}
    for x in board:
        for y in x:
            ch = chars[y]
            print(f'| {ch} |', end='')
        print('\n' + '---------------')
    print('===============')

def Clearboard(board):
    for x, row in enumerate(board):
        for y, col in enumerate(row):
            board[x][y] = 0

def winningPlayer(board, player):
    conditions = [[board[0][0], board[0][1], board[0][2]],
                     [board[1][0], board[1][1], board[1][2]],
                     [board[2][0], board[2][1], board[2][2]],
                     [board[0][0], board[1][0], board[2][0]],
                     [board[0][1], board[1][1], board[2][1]],
                     [board[0][2], board[1][2], board[2][2]],
                     [board[0][0], board[1][1], board[2][2]],
                     [board[0][2], board[1][1], board[2][0]]]

    if [player, player, player] in conditions:
        return True

    return False

def gameWon(board):
    return winningPlayer(board, 1) or winningPlayer(board, -1)

def printResult(board):
    if winningPlayer(board, 1):
        print('X has won!, Min Max  ' + '\n')

    elif winningPlayer(board, -1):
        print('O\'s have won!, Alpha Beta Pruning  ' + '\n')

    else:
        print('Draw' + '\n')

def blanks(board):
    blank = []
    for x, row in enumerate(board):
        for y, col in enumerate(row):
            if board[x][y] == 0:
                blank.append([x, y])

    return blank

def boardFull(board):
    if len(blanks(board)) == 0:
        return True
    return False

def setMove(board, x, y, player):
    board[x][y] = player

def playerMove(board):
    e = True
    moves = {1: [0, 0], 2: [0, 1], 3: [0, 2],
             4: [1, 0], 5: [1, 1], 6: [1, 2],
             7: [2, 0], 8: [2, 1], 9: [2, 2]}
    while e:
        try:
            move = int(input('Enter a number between 1-9: '))
            if move < 1 or move > 9:
                print('Invalid Move! Try again!')
            elif not (moves[move] in blanks(board)):
                print('Invalid Move! Try again!')
            else:
                setMove(board, moves[move][0], moves[move][1], 1)
                Gameboard(board)
                e = False
        except(KeyError, ValueError):
            print('Enter a number!')

def getScore(board):
    if winningPlayer(board, 1):
        return 10

    elif winningPlayer(board, -1):
        return -10

    else:
        return 0


class QLearningPlayer():
    def __init__(self):
        self.name = 'Q-Learning'
        self.q = {}
        self.init_q = 1 # "optimistic" 1.0 initial values
        self.lr = 0.3
        self.gamma = 0.9
        self.epsilon = 1.0
        self.max_epsilon = 1.0
        self.min_epsilon = 0.01
        self.decay_rate = 0.01
        self.action_n = 9
        self.win_n = 0

        self.last_state = (' ',) * 9
        self.last_action = -1

    def action(self, state, actions):
        state = tuple(state)
        self.last_state = state

        r = random.uniform(0, 1)
        if r > self.epsilon:
            if self.q.get(state):
                i = np.argmax([self.q[state][a] for a in actions])
                action = actions[i]
            else:
                self.q[state] = [self.init_q] * self.action_n
                action = random.choice(actions)
        else:
            action = random.choice(actions)

        self.last_action = action
        return action

    def reward(self, reward, state):
        if self.last_action >= 0:
            if reward == 1:
                self.win_n += 1

            state = tuple(state)
            if self.q.get(self.last_state):
                q = self.q[self.last_state][self.last_action]
            else:
                self.q[self.last_state] = [self.init_q] * self.action_n
                q = self.init_q

            self.q[self.last_state][self.last_action] = q + self.lr * (reward + self.gamma * np.max(self.q.get(state, [self.init_q]*self.action_n)) - q)

    def episode_end(self, episode):
        # epsilon decay
        self.epsilon = self.min_epsilon + (self.max_epsilon - self.min_epsilon) * np.exp(-self.decay_rate*(episode+1))

    def print_q(self):
        for k,v in self.q.items():
            print(k,v)

def minimax(state, depth, player):
    """
    AI function that choice the best move
    :param state: current state of the board
    :param depth: node index in the tree (0 <= depth <= 9),
    but never nine in this case (see iaturn() function)
    :param player: an human or a computer
    :return: a list with [the best row, best col, best score]
    """
    if player == -1:
        best = [-1, -1, -10000000]
    else:
        best = [-1, -1, +10000000]

    if depth == 0 or gameWon(state):
        score = getScore(state)
        return [-1, -1, score]

    for cell in blanks(state):
        x, y = cell[0], cell[1]
        state[x][y] = player
        score = minimax(state, depth - 1, -player)
        state[x][y] = 0
        score[0], score[1] = x, y

        if player == -1:
            if score[2] > best[2]:
                best = score  # max value
        else:
            if score[2] < best[2]:
                best = score  # min value

    return best

def abminimax(board, depth, alpha, beta, player):
    row = -1
    col = -1
    if depth == 0 or gameWon(board):
        return [row, col, getScore(board)]

    else:
        for cell in blanks(board):
            setMove(board, cell[0], cell[1], player)
            score = abminimax(board, depth - 1, alpha, beta, -player)
            if player == 1:
                # X is always the max player
                if score[2] > alpha:
                    alpha = score[2]
                    row = cell[0]
                    col = cell[1]

            else:
                if score[2] < beta:
                    beta = score[2]
                    row = cell[0]
                    col = cell[1]

            setMove(board, cell[0], cell[1], 0)

            if alpha >= beta:
                break

        if player == 1:
            return [row, col, alpha]

        else:
            return [row, col, beta]

def o_comp(board):
    if len(blanks(board)) == 9:
        #x = choice([0, 1, 2])
        #y = choice([0, 1, 2])
        move = minimax(board, len(blanks(board)), +1)
        x, y = move[0], move[1]
        setMove(board, x, y, -1)
        Gameboard(board)

    else:
        result = abminimax(board, len(blanks(board)), -inf, inf, -1)
        setMove(board, result[0], result[1], -1)
        Gameboard(board)

def x_comp(board):
    if len(blanks(board)) == 9:
        #x = choice([0, 1, 2])
        #y = choice([0, 1, 2])
        move = minimax(board, len(blanks(board)), +1)
        x, y = move[0], move[1]
        setMove(board, x, y, 1)
        Gameboard(board)

    else:
        result = abminimax(board, len(blanks(board)), -inf, inf, 1)
        setMove(board, result[0], result[1], 1)
        Gameboard(board)

def makeMove(board, player, mode):
    if mode == 1:
        if player == 1:
            minimax(board,len(blanks(board)),player)

        else:
            o_comp(board)
    else:
        if player == 1:
            o_comp(board)
        else:
            x_comp(board)

def pvc():
    currentPlayer = 1
    """while True:
        try:
            order = int(input('Enter to play 1st or 2nd: '))
            if not (order == 1 or order == 2):
                print('Please pick 1 or 2')
            else:
                break
        except(KeyError, ValueError):
            print('Enter a number')

    Clearboard(board)
    if order == 2:
        currentPlayer = -1
    else:
        currentPlayer = 1"""

    while not (boardFull(board) or gameWon(board)):
        makeMove(board, currentPlayer, 1)
        currentPlayer *= -1
        makeMove(board, currentPlayer, -1)
        currentPlayer *= 1

    printResult(board)

# Driver Code
print("=================================================")
print("TIC-TAC-TOE using MINIMAX with MIN MAX OVER ALPHA-BETA Pruning")
print("=================================================")
pvc()

TIC-TAC-TOE using MINIMAX with MIN MAX OVER ALPHA-BETA Pruning
|   ||   ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O ||   ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O ||   |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O || X |
---------------
|   || X ||   |
---------------
|   ||   ||   |
---------------
| O || O || X |
---------------
|   || X ||   |
---------------
| O ||   ||   |
---------------
| O || O || X |
---------------
| O || X ||   |
---------------
| O ||   ||   |
---------------
O's have won!, Alpha Beta Pruning  

